### ISSUE TITLE
Wrong pinning of versions

### ISSUE THREAD

**Issue by mattLLVW** [PaesslerAG/django-currentuser#30] opened 2019-05-26 15:19 UTC
It seems there's an issue with the pinning of version.

It's currently impossible to use `django-currentuser 0.4.1` with Django 2.2.1.

```commandline
ERROR: django-currentuser 0.4.1 has requirement Django<2.0,>=1.11.17, but you'll have django 2.1.8 which is incompatible.
ERROR: django-currentuser 0.4.1 has requirement Django<2.3,>=2.2.1; python_version > "3.4", but you'll have django 2.1.8 which is incompatible.
```

Step to reproduce:

```commandline
pip install django
pip install django-currentuser
```

**Comment by n-rodriguez** [comment] 2019-06-04 21:38
Neither with Django 2.2.2 :

```sh
django-currentuser 0.4.1 has requirement Django<2.0,>=1.11.17, but you'll have django 2.2.2 which is incompatible.
django-currentuser 0.4.1 has requirement Django<2.2,>=2.1.8; python_version > "3.4", but you'll have django 2.2.2 which is incompatible.
```

**Comment by belugame** [comment] 2019-06-06 09:35
One of you would like to make a pull request? I'd be happy to merge it.

**Comment by n-rodriguez** [comment] 2019-06-06 09:58
> One of you would like to make a pull request? I'd be happy to merge it.

Hi! Sorry I'm not a Python developer :/

**Comment by zsoldosp** [comment] 2019-06-12 10:54
As per https://docs.djangoproject.com/en/dev/faq/install/#what-python-version-can-i-use-with-django

2.2 Django only supports python versions 3.5 and upwards. Which python version are you using?

Also, I think this is a duplicate of #28 thus closing it here (#31 is also related)

**Closed by zsoldosp** 2019-06-12 10:54 UTC

**Comment by n-rodriguez** [comment] 2019-06-12 11:38
> Which python version are you using?

Python 3.7
