### ISSUE TITLE
Support for Django 2.2

### ISSUE THREAD

**Issue by fabio-filho** [PaesslerAG/django-currentuser#27] opened 2019-04-04 17:50 UTC
Talking about the support for Django 2.2, is there anything related on the roadmapping?

**Comment by lino** [comment] 2019-04-21 09:54
Is there even anything that needs to be done besides changing dependencies?

**Comment by djkgamc** [comment] 2019-04-22 01:15
Seems to work if you just ignore the < 2.2 requirement. Might have been a mistake

**Comment by zsoldosp** [comment] 2019-04-24 10:05
linking PR #28 to this issue

**Comment by Eorhim** [comment] 2019-05-07 07:21
This is addressed in pull request #29. It was slightly more involved than just updating the referenced versions, but no big deal.

**Comment by zsoldosp** [comment] 2019-06-12 10:56
As per https://docs.djangoproject.com/en/dev/faq/install/#what-python-version-can-i-use-with-django

2.2 Django only supports python versions 3.5 and upwards. Which python version are you using? #29 seems to have set it up correctly to me

(copying comment from duplicate issue #30 and PR #31 is also related)

**Comment by zsoldosp** [comment] 2019-06-12 15:32
I think the root cause of the problem is that the first line of the install_requires is not bound by python version, thus always gets applied (from #31 comment)

**Comment by serafss2** [comment] 2019-07-09 11:41
Pull request #33 should fix this issue

**Comment by serafss2** [comment] 2019-07-18 18:11
I just tested, it's fixed in `0.4.2`, this can be closed

**Closed** 2019-07-18 21:31 UTC
